services:
  app:
    build: .
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    environment:
      - MODE=local
    ports:
      - "8000:8000"

  ngrok:
    image: ngrok/ngrok:latest
    command: http app:8000 --url=${NGROK_DOMAIN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - app
    ports:
      - "4040:4040"
